### ISSUE TITLE
There are no instructions !!!

### ISSUE THREAD

**Issue by Nio9345** [iYato/chocolatey-packages#2]
I really want to try this tool/package but there are no instructions anywhere in order to automate the installation of the Office suite. The package essentially install only the Deployment tool.

**Comment by iyato** [comment]
Sorry for the late response. The `office-tool` package will not install the Office suite directly, it's used to install `Office Tool Plus` via chocolatey and you could install the Office suite by `Office Tool Plus`. Here is the official documentation: https://help.coolhub.top/
